GGIR_ENMO = Average ENMO in g (gravity)
(Start: March 2020 -> (corona))

Import all libraries
```{r}
library(data.table)
library(plyr)
library(plotrix)
library(datasets)
library(tidyverse)
library(ggplot2)
```

load and transform data
```{r}
load("C:/Users/mjbur/Desktop/SHARE/merged_data_de.rda")

variables <- c("mergeid", "GGIR_ENMO", "ph006d19", "ph006d20", "age", "female",
               "maxgrip")
datac <- all_data[variables]

# drop the lines with maxgrip < 0
datac <- datac[!(datac$maxgrip <= 0),]
dt_de <- data.table(datac)

# merging the ENMO scores for each mergeid with the mean of all scores
dt_de <- (dt_de[,list(GGIR_ENMO = mean(GGIR_ENMO)),
                  by = c("mergeid", "ph006d19", "ph006d20","age", "female", "maxgrip")]
)
```

```{r}
summary(dt_de$GGIR_ENMO)
describe(dt_de$GGIR_ENMO)
```

  Sum male/female mean of ENMO Score
   
```{r}
sum_sex <- (dt_de[,list(N = length(GGIR_ENMO),
                        min = min(GGIR_ENMO), max = max(GGIR_ENMO),
                        mean = mean(GGIR_ENMO), median = median(GGIR_ENMO),
                        sd   = sd(GGIR_ENMO), se = std.error(GGIR_ENMO),
                        ci = std.error(GGIR_ENMO) * qt(.95/2 + .5, length(GGIR_ENMO))),
                        by = "female"]
)
```
 
 Plot male/female mean of ENMO Score 
   0: male, 1:female
```{r}
ggplot(sum_sex, aes(x=female, y=mean , fill=factor(female))) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=mean-ci, ymax=mean+ci),
                size =.3,
                width =.2, 
                position=position_dodge(.9)) +
  xlab("sex") +
  ylab("ENMO Score mean") + 
  scale_fill_hue(name=" ", labels=c("male","female"))
```

 Enmo Score with & without rheuma
 (if RA=1 or RO=1 -> rheuma = yes)
 
```{r}
rheuma_data <- (dt_de[,list(N = length(GGIR_ENMO),
                         min = min(GGIR_ENMO),
                         max = max(GGIR_ENMO),
                         mean = mean(GGIR_ENMO),
                         median = median(GGIR_ENMO),
                         sd   = sd(GGIR_ENMO),
                         se = std.error(GGIR_ENMO),
                         ci = std.error(GGIR_ENMO) * qt(.95/2 + .5, length(GGIR_ENMO))),
                         by = c("age","ph006d19", "ph006d20")]
)
```
 
 scatterplot:
 
```{r}
rheuma_data <- tbl_df(rheuma_data)
rheuma_data %>%
  mutate(rheuma = ifelse(ph006d19 == 1 | ph006d20 == 1, 'yes', 'no')) %>%
  #mutate(sex = ifelse(female == 1, 'f', 'm')) 
    ggplot(aes(x=age,y=mean, color=rheuma)) + 
    geom_point() +
    ggtitle('Differences in activity with and without rheuma depending on age') +
    ylab('mean of ENMO (gravity)') +
    geom_smooth(method = 'lm', se=TRUE) #se = TRUE -> with 95 conf. interval

```
 
  ENMO and max grip
  
```{r}
grip_rheuma <- (dt_de[,list(N = length(GGIR_ENMO),
                            min = min(GGIR_ENMO),
                            max = max(GGIR_ENMO),
                            mean = mean(GGIR_ENMO),
                            median = median(GGIR_ENMO),
                            sd   = sd(GGIR_ENMO),
                            se = std.error(GGIR_ENMO),
                            ci = std.error(GGIR_ENMO) * qt(.95/2 + .5, length(GGIR_ENMO))),
                      by = c("maxgrip","ph006d19", "ph006d20")]
)
```

  scatterplot:
  
```{r}
grip_rheuma <- tbl_df(grip_rheuma)
grip_rheuma %>%
  mutate(rheuma = ifelse(ph006d19 == 1 | ph006d20 == 1, 'yes', 'no')) %>%
  ggplot(aes(x=maxgrip,y=mean, color=rheuma)) + 
  geom_point() +
  ggtitle('Differences in activity with and without rheuma depending on age') +
  ylab('mean of ENMO (gravity)') +
  geom_smooth(method = 'lm', se=TRUE) #se = TRUE -> with 95 conf. interval
```